baseURL = "/"
languageCode = "en-us"
title = "Tom Dalby"
copyright = "Copyright (c) 2017, all rights reserved."
# canonifyurls = true
paginate = 3
# theme = "hugo-dusk"
theme = "hugo-future-imperfect"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "Tom Dalby"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsCodeFences = true
# pygmentsUseClasses = true
pygmentsStyle = "manni"

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "posts"
  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "A sporadic dev blog."

[params]
  github = "thomasjackdalby"
  gitlab = "gitlab id"
  twitter = "twitter id"
  linkedin = "linkedin id"
  email = "myemail"
  useChroma = true
  
[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#67e5ee"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color