baseurl = "https://thomasjackdalby.github.io"
title = "thomasjackdalby"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20

pygmentsstyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disqusShortname = "yourdiscussshortname"

[params]
    author = "Thomas Jack Dalby"
    info = "Engineer. Consultant. Developer."
    description = "Projects and development blog."
    keywords = "blog,developer,personal"
    avatarurl = "images/profile.png"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
    footercontent = "Any fool can write code that a computer can understand. Good programmers write code that humans can understand. -Martin Fowler"
    hidecredits = false
    hidecopyright = false

    rtl = false
    inverted = true
    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/thomasjackdalby/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/thomas-jack-dalby-3597398a/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/ThomasJackDalby"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"